config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                 registrations: 'users/registrations' }

  root 'items#index'
  resources :users do
    collection do
      get 'signup'
      get 'mypage_card'
      get 'log_out'
      post 'pay'
    end
  end
  resources :items do
    collection do
      get 'edit_user_info'
      get 'profile_edit'
      get 'purchase'
      get 'search'
      get 'item_confirmation'
    end
  end
  namespace :api do
    resources :items, only: :new, defaults: {format: 'json'}
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

   resources :purchase, only: [:index] do
      collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
      end
    end

  resources :exchanges, only: [:show] do
    collection do
      get 'listing_confirmation'
      get 'trading'
      get 'sold'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :items
  has_many :images
  has_many :sns_credentials, dependent: :destroy
  validates :nickname, presence: true, length: { maximum: 6 }

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present? 
      user = User.where(id: snscredential.user_id).first
      unless user.present? 
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential
    else 
      user = User.where(email: auth.info.email).first
      if user.present? 
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else 
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
      end
    end
    return { user: user , sns_id: sns.id }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"])
    @user = info[:user]
    sns_id = info[:sns_id]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.sns_id"] = sns_id
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
   def create
     if params[:user][:password] == "" 
       params[:user][:password] = "Devise.friendly_token.first(6)"
       params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
       super
       sns = SnsCredential.update(user_id:  @user.id)
     else 
       super
     end
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_parent

  def signup
  end

  def mypage_card
  end


  def mypage_card_create
  end

  def show

  end

  def log_out
  end

  def set_parent
    @parents = Category.where(ancestry: nil)
  end

end

app/views/users/listing_confirmation.html.haml
.toppage-header
  = render 'shared/header'
.main-content
  = render 'shared/sidebar'

  -#右側のコンテンツ
  .main-content_right
    .main-content_right-contents
      .under_contents
        .under_contents_head 出品した商品
        .listing_confirmation
          .listing_confirmation_left.listing-box.choice
            = link_to " 出品中", listing_confirmation_users_path
          .listing_confirmation_center.listing-box.not-choice
            = link_to "取引中", trading_users_path
          .listing_confirmation_right.listing-box.not-choice
            = link_to "売却済み", sold_users_path
        -#右側コンテンツ 上から2個目  body部分
        - if @items.present?
          - @items.each do |item|
            .main-content_right-contents-body_list
              = link_to item_confirmation_items_path(item) do
                .mypage-confirmation-link
                  = image_tag item.images.first, class:"mypage-confirmation-image"
                  .mypage-confirmation-body
                    .mypage-confirmation-body-title
                      = item.name
                    .mypage-confirmation-body-inner
                      .mypage-confirmation-body-inner-like
                        .fa.fa-heart-o
                        .mypage-confirmation-body-inner-like-num 0
                      .mypage-confirmation-body-inner-comment
                        .fa.fa-comment-o
                        .mypage-confirmation-body-inner-comment-num 0
                      .mypage-confirmation-body-inner-text 出品中
                  .fas.fa-chevron-right
          = paginate(@items)
        - else
          .under_contents_body
.toppage-aside
  = render 'shared/aside'

.toppage-footer
  = render 'shared/footer'

= link_to new_item_path do
  .footer-sell-btn
    .footer-sell-box
      .sell-text 出品
      .fa.fa-camera

app/views/users/log_out.html.haml
.toppage-header
  = render 'shared/header'
%nav.main-content__breadcrumb
  - breadcrumb :log_out
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fas fa-chevron-right')}"
.main-content
  = render 'shared/sidebar'
  .main-content_right
    %ul.logout-content
      %li.logout-content__box
        =link_to  "ログアウト", destroy_user_session_path, method: :delete, class:".logout-content__box__btn" 
.toppage-aside
  = render 'shared/aside'
.toppage-footer
  = render 'shared/footer'

= link_to new_item_path do
  .footer-sell-btn
    .footer-sell-box
      .sell-text 出品
      .fa.fa-camera

app/views/users/mypage.html.haml
.toppage-header
  = render 'shared/header'
.main-content
  = render 'shared/sidebar'

  -#右側のコンテンツ
  .main-content_right
    %section.main-content_right-contents

      -#右側コンテンツヘッダー部分
      .main-content_right-contents_header
        .main-content_right-contents_header-link
          %figure
            .figure-icon
            = link_to "https://www.mercari.com/jp/u/379323571/"
          %h3.bold
            湯豆腐
          .main-content_right-contents_header-link-number
            %div
              評価
              %span.bold 0
            %div
              出品数
              %span.bold 0

      .main-content_right-contents-body
        -#右側コンテンツ タブ部分
        %ul.main-content_right-contents-tab
          %li
            .main-content_right-contents-tab_left
              %h3
                = link_to " お知らせ","#"
          %li
            .main-content_right-contents-tab_right
              %h3
                = link_to "やることリスト","#"

          -#  右側コンテンツ body部分
        %ul.main-content_right-contents-body_list
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "事務局から個別メッセージ「Googleログイン通知」","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "あと3日！》セブン−イレブンの揚げ物が¥11！お店で使えるクーポンを配信中！","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "明日、300Pの有効期限が切れます","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "事務局からメッセージ【P300獲得！】欲しかったあの商品をお得にゲットしませんか？","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "《大好評》必ずもらえる買う買うキャンペーン開催中！","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right

        -#右側コンテンツ 上から2個目
      %section.under_contents
        %h4.under_contents_head 購入した商品
        %ul.main-content_right-contents-tab
          %li
            .main-content_right-contents-tab_left
              = link_to " 取引中","#"
          %li
            .main-content_right-contents-tab_right
              = link_to "過去の取引","#"
        -#右側コンテンツ 上から2個目  body部分
        .under_contents_body
.toppage-aside
  = render 'shared/aside'

.toppage-footer
  = render 'shared/footer'
.footer-sell-btn
  = link_to "#" do
    .sell-text 出品
    .fa.fa-camera

app/views/users/mypage_card.html.haml
.mypage-card-create-container
  .card-create-header
    = render 'shared/header'
  %nav.main-content__breadcrumb
    - breadcrumb :mypage_card
    = breadcrumbs separator: "#{content_tag(:i, '', class: 'fas fa-chevron-right')}"
  .card-create-main.center
    .content-box
      .card-create-side
        = render 'shared/sidebar'
      .card-content
        .card-content__upper__box
          %h2.card-content__upper__box__title 支払い方法
        .card-content__middle__box
          .card-content__middle__box__index
            %h3 クレジットカード一覧
            .card-content__middle__box__index__reguration
              %li.card-content__middle__box__index__reguration__btn
                %i.far.fa-credit-card
                =link_to  "クレジットカードを追加する", new_card_path, method: :get
        .card-content__bottom__box
          .card-content__bottom__box__infomation
            =link_to "支払い方法について", "#"
            =fa_icon("chevron-right")

  .toppage-aside
    = render 'shared/aside'
  .toppage-footer
    = render 'shared/footer'

  = link_to new_item_path do
    .footer-sell-btn
      .footer-sell-box
        .sell-text 出品
        .fa.fa-camera

app/views/users/mypage_card_create.html.haml
.mypage-card-create-container
  .card-create-header
    = render 'shared/header' 
    %nav.header-card
      %ul
        %li
          =link_to "メルカリ", "#"
          =fa_icon("angle-right")
        %li
          =link_to "マイページ", "#"
          =fa_icon("angle-right")
        %li
          =link_to "支払い方法", "#"
          =fa_icon("angle-right")
        %li
          %span クレジットカード情報入力
  .card-create-main.center
    .content-box
      .card-create-side
        = render 'shared/sidebar'
      .card-registration
        %h2.card-registration__title クレジットカード情報入力

        %form.card-registration__form#charge-form{action:"/pay", method: :post}
          .content__box
            .content__box__group
              %label カード番号
              %span.content__box__group__form__require 必須
              %br
              %input.content__box__group__input{"data-input-type" => "card", maxlength: "16", placeholder: "半角数字のみ", type: "text", value:  "",name: "number",id: "payment_card_no"}/
              %ul.content__box__group__card__list
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?4194600336", height:"20", width: "49")
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?4194600336", height:"20", width: "34")
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?4194600336", height:"20", width: "30")  
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?4194600336", height: "20", width: "32") 
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?4194600336", height: "20", width: "21")  
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?4194600336", height: "20", width: "32")
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?4194600336", height: "20", width: "32") 
              .content__box__expire
                %label{for: "payment_card_expire"} 有効期限
                %span.content__box__expire__require 必須
                %br/
                .content__box__expire__box
                  .content__box__expire__box__month
                    %select.exp_month{name: "exp_month",id: "payment_card_expire_mm"}
                      %option{value:  "01"} 01
                      %option{value:  "02"} 02
                      %option{value:  "03"} 03
                      %option{value:  "04"} 04
                      %option{value:  "05"} 05
                      %option{value:  "06"} 06
                      %option{value:  "07"} 07
                      %option{value:  "08"} 08
                      %option{value:  "09"} 09
                      %option{value:  "10"} 10
                      %option{value:  "11"} 11
                      %option{value:  "12"} 12
                  %p 月
                .content__box__expire__box
                  .content__box__expire__box__year
                    %select.exp_year{name: "exp_year",id: "payment_card_expire_yy"}
                      %option{value:  "2019"} 19
                      %option{value:  "2020"} 20
                      %option{value:  "2021"} 21
                      %option{value:  "2022"} 22
                      %option{value:  "2023"} 23
                      %option{value:  "2024"} 24
                      %option{value:  "2025"} 25
                      %option{value:  "2026"} 26
                      %option{value:  "2027"} 27
                      %option{value:  "2028"} 28
                      %option{value:  "2029"} 29
                  %p 年
              .content__box__secure
                %label{for:  "payment_card_security_code"} セキュリティコード
                %span.content__box__secure__require 必須
                %input.content__box__secure__default{placeholder: "カード背面4桁もしくは3桁の番号", type:  "number", value:  "",name: "cvc",id: "payment_card_security_code"}/
                .content__box__secure__box
                  .content__box__secure__box__text{"data-js" => "show-tips-toggle"}
                    %span
                      =fa_icon("question-circle")
                    カード裏面の番号とは？
    
                  .content__box__secure__box__hidden{"data-js" => "show-tips-content"}
                    カードの裏面をご参照ください。
                    %br/
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?4194600336", :width => "240"
                %button.btn-default.btn-red{type: "submit",id: "submit-button"} 追加する
                / 今回はHTML上に結果を表示します
                生成されたトークン：
                #card_token

            %script{async:   "", src:  "https://www.google-analytics.com/plugins/ua/ec.js", type:  "text/javascript"}
            %script{async:   "", src:  "https://www.google-analytics.com/analytics.js", type:  "text/javascript"}
            %script{async:   "", src:  "//www.googleadservices.com/pagead/conversion_async.js", type:  "text/javascript"}
            %script{async:   "", src:  "https://www.googletagmanager.com/gtm.js?id=GTM-KLPT5L5"}
            %script{async:   "", src:  "https://p01.mul-pay.jp/ext/js/token.js"}
            %script{async:   "", src:  "//www-mercari-jp.akamaized.net/assets/js/get_gmopg_card_token.js?3335479155"}
            %script{src:  "https://googleads.g.doubleclick.net/pagead/viewthroughconversion/880621981/?random=1556522409982&cv=9&fst=1556522409982&num=1&guid=ON&resp=GooglemKTybQhCsO&u_h=900&u_w=1440&u_ah=806&u_aw=1440&u_cd=24&u_his=3&u_tz=540&u_java=false&u_nplug=3&u_nmime=4&gtm=2wg430&sendb=1&frm=0&url=https%3A%2F%2Fwww.mercari.com%2Fjp%2Fmypage%2Fcard%2Fcreate%2F&ref=https%3A%2F%2Fwww.mercari.com%2Fjp%2Fmypage%2Fcard%2F&tiba=%E3%82%AF%E3%83%AC%E3%82%B8%E3%83%83%E3%83%88%E3%82%AB%E3%83%BC%E3%83%89%E6%83%85%E5%A0%B1%E5%85%A5%E5%8A%9B%20-%20%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA%20%E3%82%B9%E3%83%9E%E3%83%9B%E3%81%A7%E3%81%8B%E3%82%93%E3%81%9F%E3%82%93%20%E3%83%95%E3%83%AA%E3%83%9E&async=1&rfmt=3&fmt=4"}
  .toppage-aside
    = render 'shared/aside'
  .toppage-footer
    = render 'shared/footer'

  = link_to new_item_path do
    .footer-sell-btn
      .footer-sell-box
        .sell-text 出品
        .fa.fa-camera

app/views/users/show.html.haml
.toppage-header
  = render 'shared/header'
%nav.main-content__breadcrumb
  - breadcrumb :users
  = breadcrumbs separator: "#{content_tag(:i, '', class: 'fas fa-chevron-right')}"
.main-content
  = render 'shared/sidebar'
  -#右側のコンテンツ
  .main-content_right
    %section.main-content_right-contents

      -#右側コンテンツヘッダー部分
      .main-content_right-contents_header
        .main-content_right-contents_header-link
          %figure
            .figure-icon
            = link_to "https://www.mercari.com/jp/u/379323571/"
          %h3.bold
            =current_user.nickname
          .main-content_right-contents_header-link-number
            %div
              評価
              %span.bold 0
            %div
              出品数
              %span.bold 0

      .main-content_right-contents-body
        -#右側コンテンツ タブ部分
        %ul.main-content_right-contents-tab
          %li.main-content_right-contents-tab_left
            = link_to " お知らせ","#"
          %li.main-content_right-contents-tab_right
            = link_to "やることリスト","#"

          -#  右側コンテンツ body部分
        %ul.main-content_right-contents-body_list
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "事務局から個別メッセージ「Googleログイン通知」","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "あと3日！》セブン−イレブンの揚げ物が¥11！お店で使えるクーポンを配信中！","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "明日、300Pの有効期限が切れます","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "事務局からメッセージ【P300獲得！】欲しかったあの商品をお得にゲットしませんか？","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
          %li
            .mypage-item-link
              .list_icon
              .mypage-item-body
                .mypage-item-text
                  = link_to "《大好評》必ずもらえる買う買うキャンペーン開催中！","https://www.mercari.com/jp/mypage/news/"
                %time
                  %i.far.fa-clock
                  %span 1時間前
                %i.fas.fa-chevron-right
        .maypage__go-list
          .maypage__go-list__box 一覧を見る

        -#右側コンテンツ 上から2個目
      %section.under_contents
        %h4.under_contents_head 購入した商品
        %ul.main-content_right-contents-tab
          %li.main-content_right-contents-tab_left
            = link_to " 取引中","#"
          %li.main-content_right-contents-tab_right
            = link_to "過去の取引","#"
        -#右側コンテンツ 上から2個目  body部分
        .under_contents_body
.toppage-aside
  = render 'shared/aside'

.toppage-footer
  = render 'shared/footer'

= link_to new_item_path do
  .footer-sell-btn
    .footer-sell-box
      .sell-text 出品
      .fa.fa-camera

app/views/users/signup.html.haml
.content
  .user-header
    = link_to root_path do
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?570108281"
.user-content
  %section.user-content__container
    %h2.user-content__container__head 新規会員登録
    .user-content__container__inner
      .user-content__container__inner__content
        =link_to new_user_session_path, class:"btn-default btn-mail" do
          =fa_icon 'envelope'
          メールアドレスで登録
        = link_to  user_facebook_omniauth_authorize_path, id:"facebook-login", class:"btn-default btn-sns btn-sns-facebook" do
          =fa_icon 'facebook-square'
          %p Facebookで登録
      
        = link_to user_google_oauth2_omniauth_authorize_path, id:"google-login", class:"btn-default btn-sns btn-sns-google" do
          = image_tag "https://img.icons8.com/color/48/000000/google-logo.png"
          %p Googleで登録

%footer.user-footer
  %nav
    %ul.clearfix
      %li
        = link_to 'プライバシーポリシー', 'https://www.mercari.com/jp/privacy/'
      %li
        = link_to 'メルカリ利用規約', 'https://www.mercari.com/jp/tos/'
      %li
        = link_to '特定商取引に関する表記', 'https://www.mercari.com/jp/tokutei/'

  = link_to "https://www.mercari.com/jp/" do
    = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?570108281" , class:"footer_img"
  %p
    %small © 2019 Mercari

app/views/users/sold.html.haml
.toppage-header
  = render 'shared/header'
.main-content
  = render 'shared/sidebar'

  -#右側のコンテンツ
  .main-content_right
    .main-content_right-contents
      .under_contents
        .under_contents_head 出品した商品
        .listing_confirmation
          .listing_confirmation_left.listing-box.not-choice
            = link_to " 出品中", listing_confirmation_users_path
          .listing_confirmation_center.listing-box.not-choice
            = link_to "取引中", trading_users_path
          .listing_confirmation_right.listing-box.choice
            = link_to "売却済み", sold_users_path
        -#右側コンテンツ 上から2個目  body部分
        .under_contents_body
.toppage-aside
  = render 'shared/aside'

.toppage-footer
  = render 'shared/footer'

= link_to new_item_path do
  .footer-sell-btn
    .footer-sell-box
      .sell-text 出品
      .fa.fa-camera

app/views/users/trading.html.haml
.toppage-header
  = render 'shared/header'
.main-content
  = render 'shared/sidebar'

  -#右側のコンテンツ
  .main-content_right
    .main-content_right-contents
      .under_contents
        .under_contents_head 出品した商品
        .listing_confirmation
          .listing_confirmation_left.listing-box.not-choice
            = link_to " 出品中", listing_confirmation_users_path
          .listing_confirmation_center.listing-box.choice
            = link_to "取引中", trading_users_path
          .listing_confirmation_right.listing-box.not-choice
            = link_to "売却済み","#"
        -#右側コンテンツ 上から2個目  body部分
        .under_contents_body
.toppage-aside
  = render 'shared/aside'

.toppage-footer
  = render 'shared/footer'

= link_to new_item_path do
  .footer-sell-btn
    .footer-sell-box
      .sell-text 出品
      .fa.fa-camera