config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                 registrations: 'users/registrations' }

  root 'items#index'
  resources :users do
    collection do
      get 'signup'
      get 'mypage_card'
      get 'log_out'
      post 'pay'
    end
  end
  resources :items do
    collection do
      get 'edit_user_info'
      get 'profile_edit'
      get 'purchase'
      get 'search'
      get 'item_confirmation'
    end
  end
  namespace :api do
    resources :items, only: :new, defaults: {format: 'json'}
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

   resources :purchase, only: [:index] do
      collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
      end
    end

  resources :exchanges, only: [:show] do
    collection do
      get 'listing_confirmation'
      get 'trading'
      get 'sold'
    end
  end
end

app/views/shared/_aside.html.haml
.aside-box{style:"background-image: url(#{image_path('aside.jpg')})"}
  .aside-box__left
    %h2.aside-box__left__title スマホでかんたんフリマアプリ
    .aside-box__left__content 今すぐ無料ダウンロード！
    .aside-box__left__icons
      .aside-box__left__icons__figre
        = image_tag src="//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?1107552019", id:"aside-left-figure"
      .aside-box__left__icons__store
        = link_to (image_tag src="app-store.svg"), "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", target:"_blank", class:"app-store"
        = link_to (image_tag src="google-play.svg"), "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", target:"_blank", class:"google-play"
  .aside-box__right
    = image_tag src="//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?1107552019", id:"aside-right-pic"

app/views/shared/_confirmation.html.haml
.main-content_right-contents
  .under_contents
    .under_contents_head 出品した商品
    .listing_confirmation
      - if current_page?(:action => 'trading')
        .listing_confirmation_left.listing-box
          = link_to "出品中", listing_confirmation_exchanges_path
        .listing_confirmation_center.listing-box.choice
          = link_to "取引中", trading_exchanges_path
        .listing_confirmation_right.listing-box
          = link_to "売却済み", sold_exchanges_path
      - elsif current_page?(:action => 'sold')
        .listing_confirmation_left.listing-box
          = link_to "出品中", listing_confirmation_exchanges_path
        .listing_confirmation_center.listing-box
          = link_to "取引中", trading_exchanges_path
        .listing_confirmation_right.listing-box.choice
          = link_to "売却済み", sold_exchanges_path
      - else
        .listing_confirmation_left.listing-box.choice
          = link_to " 出品中", listing_confirmation_exchanges_path
        .listing_confirmation_center.listing-box
          = link_to "取引中", trading_exchanges_path
        .listing_confirmation_right.listing-box
          = link_to "売却済み", sold_exchanges_path

app/views/shared/_footer.html.haml
.footer-box
  .footer-box__merukari
    %h2.footer-box__merukari--title メルカリについて
    %ul
      %li
        = link_to '会社概要（運営会社）', "https://about.mercari.com/", target:"_blank"
      %li
        = link_to '採用情報', "https://careers.mercari.com/", target:"_blank"
      %li
        = link_to 'プレスリリース', "https://about.mercari.com/press/news/", target:"_blank"
      %li
        = link_to '公式ブログ', "https://jp-news.mercari.com/", target:"_blank"
      %li
        = link_to 'メルカリロゴ利用ガイドライン', "https://www.mercari.com/jp/logo-guidelines/", target:"_blank"
    .footer-box__merukari__icon
      .footer-box__merukari__icon--twitter
        = link_to (image_tag src="twitter.png", width:"50px", class:"twitter-icon"), "https://twitter.com/mercari_jp", target:"_blank"
      .footer-box__merukari__icon--facebook
        = link_to (image_tag src="facebook.png", width:"26px", class:"facebook-icon"), "https://www.facebook.com/mercarijp", target:"_blank"

  .footer-box__help
    %h2.footer-box__help--title ヘルプ&ガイド
    %ul
      %li
        = link_to 'メルカリガイド', "https://www.mercari.com/jp/help_center/", target:"_blank"
      %li
        = link_to 'らくらくメルカリ便', "https://www.mercari.com/jp/rakuraku-mercari/", target:"_blank"
      %li
        = link_to 'ゆうゆうメルカリ便', "https://www.mercari.com/jp/yuyu-mercari/", target:"_blank"
      %li
        = link_to '大型メルカリ便', "https://www.mercari.com/jp/rakuraku-ogata/", target:"_blank"
      %li
        = link_to '車体取引ガイド', "https://www.mercari.com/jp/guide/car/", target:"_blank"
      %li
        = link_to 'メルカリあんしん・あんぜん宣言！', "https://www.mercari.com/jp/safe/description/", target:"_blank"
      %li
        = link_to '偽ブランド品撲滅への取り組み', "https://www.mercari.com/jp/authenticity/", target:"_blank"
      %li
        = link_to 'メルカリボックス', "https://www.mercari.com/jp/box/", target:"_blank"

  .footer-box__privacy
    %h2.footer-box__privacy--title プライバシーと利用規約
    .footer-box__privacy__box
      %ul.footer-box__privacy__box__left
        %li
          = link_to 'プライバシーポリシー', "https://www.mercari.com/jp/privacy/", target:"_blank"
        %li
          = link_to 'メルカリ利用規約', "https://www.mercari.com/jp/tos/", target:"_blank"
        %li
          = link_to 'あんしんスマホサポート制度に関する利用特約', "https://www.mercari.com/jp/tos_smartphone_support/", target:"_blank"
        %li
          = link_to 'コンプライアンスポリシー', "https://www.mercari.com/jp/compliance/", target:"_blank"
      %ul.footer-box__privacy__box__right
        %li
          = link_to '個人データの安全管理に係る基本方針', "https://www.mercari.com/jp/data_security/", target:"_blank"
        %li
          = link_to '特定商取引に関する表記', "https://www.mercari.com/jp/tokutei/", target:"_blank"
        %li
          = link_to '資金決済法に基づく表示', "https://www.mercari.com/jp/shikin_kessai/", target:"_blank"
        %li
          = link_to '法令順守と犯罪抑止のために', "https://about.mercari.com/csr/safety/", target:"_blank"
        %li
          = link_to '返品・返金ポリシー', "https://www.mercari.com/jp/help_center/category/458/", target:"_blank"

  .footer-box__country
    %h2.footer-box__country--title 国
    %ul
      %li
        = link_to '日本', "https://www.mercari.com/jp/", target:"_blank"
      %li
        = link_to 'United States', "https://www.mercari.com/", target:"_blank"
.footer-bottom
  .footer-bottom__text
    &copy; 2019 Mercari
    .footer-bottom__text__logo
      = image_tag src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?1414406813", width:"120"

app/views/shared/_header.html.haml
.header-box
  .header-box__top
    = link_to (image_tag src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1107552019", alt:"merukari", class:"header-icon"), root_path
    %form.header-box__top__form
    = form_tag('/items/search',method: :GET) do
      %input{placeholder:"何かお探しですか？", type:"search", name:"keyword", class:"input-default"}
      = button_tag type: "submit", class: "header-box__top__form__btn" do
        =fa_icon 'search lg'
  .header-box__bottom
    %ul#dropmenu.header-box__bottom__left
      %li
        = link_to "カテゴリーから探す", "#", id:"search-category", class:"fa fa-list-ul"
        %ul
          - @parents.each do |parent|
            %li
              = link_to "#" do
                = parent.name
              %ul
                - parent.children.each do |child|
                  %li
                    = link_to "#" do
                      = child.name
                    %ul
                      - child.children.each do |grandchild|
                        %li
                          = link_to "#" do
                            = grandchild.name

      %li
        = link_to "ブランドから探す", "#", id:"search-brand", class:"fa fa-tag"
        %ul
          %li
            = link_to "サブメニュー", "#"
          %li
            = link_to "サブメニュー", "#"
          %li
            = link_to "サブメニュー", "#"
          %li
            = link_to "サブメニュー", "#"
    -if user_signed_in?
      %ul#dropmenu.header-box__bottom__right
        %li
          = link_to "お知らせ", "#", id:"news", class:"fa fa-bell-o"
        %li
          = link_to "やることリスト", "#", id:"todos", class:"fa fa-check"
        %li.mypage-icon
          = image_tag src="mypage.png", id:"mypage-icon"
          = link_to "マイページ", user_path(current_user), id:"mypage"
        .header-box__bottom__right__news
        .header-box__bottom__right__todo
        .header-box__bottom__right__mypage
    -else 
      %ul.header-box__bottom__devise__right
        %li.signin-btn.center
          = link_to "ログイン", new_user_session_path 
        %li.signup-btn.center
          = link_to "新規会員登録", signup_users_path

app/views/shared/_main.html.haml
%section.swiper-container
  .swiper-wrapper
    #slide1.swiper-slide{style:"background-image: url(#{image_path('o-rora.jpg')})"}
    #slide2.swiper-slide{style:"background-image: url(#{image_path('amanogawa.jpg')})"}
    #slide3.swiper-slide{style:"background-image: url(#{image_path('ginga.jpg')})"}

  .swiper-pagination

  .swiper-button-prev
  .swiper-button-next

  .swiper-scrollbar

%section.pickup-container
  .pickup-head ピックアップカテゴリー
  %section.items-box-container
    .text-center
      = link_to "レディース 新着アイテム", "/jp/category/1/"
    .items-box-content.clearfix
      - @ladys.each do |item|
        %section.items-box
          = link_to item_path(item) do
            .items-box-photo
              - if item.trade == true
                .sold-out
              = image_tag item.images.first, class:"items-photo"
            .items-box-body
              .items-box-name
                = item.name
              .items-box-num
                .items-box-price.font-5
                  .yen-mark ¥
                  = number_with_delimiter(item.price)
                .todo-icon
                  .fa.fa-heart-o
                  %span 1
              .item-box-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", "#"
  %section.items-box-container.clearfix
    .text-center
      = link_to "メンズ 新着アイテム", "/jp/category/2/"
    .items-box-content.clearfix
      - @mens.each do |item|
        %section.items-box
          = link_to item_path(item) do
            .items-box-photo
              - if item.trade == true
                .sold-out
              = image_tag item.images.first, class:"items-photo"
            .items-box-body
              .items-box-name
                = item.name
              .items-box-num
                .items-box-price.font-5
                  .yen-mark ¥
                  = number_with_delimiter(item.price)
                .todo-icon
                  .fa.fa-heart-o
                  %span 1
              .item-box-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", "#"
  %section.items-box-container.clearfix
    .text-center
      = link_to "本・音楽・ゲーム 新着アイテム", "/jp/category/3/"
    .items-box-content.clearfix
      - @books.each do |item|
        %section.items-box
          = link_to item_path(item) do
            .items-box-photo
              - if item.trade == true
                .sold-out
              = image_tag item.images.first, class:"items-photo"
            .items-box-body
              .items-box-name
                = item.name
              .items-box-num
                .items-box-price.font-5
                  .yen-mark ¥
                  = number_with_delimiter(item.price)
                .todo-icon
                  .fa.fa-heart-o
                  %span 1
              .item-box-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", "#"
  %section.items-box-container.clearfix
    .text-center
      = link_to "おもちゃ・ホビー・グッズ 新着アイテム", "/jp/category/6/"
    .items-box-content.clearfix
      - @hobbys.each do |item|
        %section.items-box
          = link_to item_path(item) do
            .items-box-photo
              - if item.trade == true
                .sold-out
              = image_tag item.images.first, class:"items-photo"
            .items-box-body
              .items-box-name
                = item.name
              .items-box-num
                .items-box-price.font-5
                  .yen-mark ¥
                  = number_with_delimiter(item.price)
                .todo-icon
                  .fa.fa-heart-o
                  %span 1
              .item-box-tax
                (税込)
    .view-all
      = link_to "すべての商品を見る", "#"

app/views/shared/_sidebar.html.haml
-# サイドバー部分
.main-content_left
  %ul.main-content_left-list
    %li.main-content_left-list_mypage
      = link_to user_path(current_user), id:"mypage" do
        .main-content_left-list-item
          マイページ
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          お知らせ
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          やる事リスト
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          いいね一覧
          %i.fas.fa-chevron-right
    %li
      = link_to new_item_path do
        .main-content_left-list-item
          出品する
          %i.fas.fa-chevron-right
    %li
      = link_to listing_confirmation_exchanges_path do
        .main-content_left-list-item
          出品した商品ー出品中
          %i.fas.fa-chevron-right
    %li
      = link_to trading_exchanges_path do
        .main-content_left-list-item
          出品した商品ー取引中
          %i.fas.fa-chevron-right
    %li
      = link_to sold_exchanges_path do
        .main-content_left-list-item
          出品した商品ー売却済み
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          購入した商品ー取引中
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          購入した商品ー過去の取引
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          ニュース一覧
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          評価一覧
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          ガイド
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          お問い合わせ
          %i.fas.fa-chevron-right

  %h3.main-content_left-nav
    メルペイ
  %ul.main-content_left-list
    %li
      = link_to '#' do
        .main-content_left-list-item
          売上・振込申請
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          ポイント
          %i.fas.fa-chevron-right

  %h3.main-content_left-nav
    設定
  %ul.main-content_left-list
    %li
      = link_to '#' do
        .main-content_left-list-item
          プロフィール
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
    %li
      = link_to mypage_card_users_path do
        .main-content_left-list-item
          お支払い方法
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          メール/パスワード
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          本人情報
          %i.fas.fa-chevron-right
    %li
      = link_to '#' do
        .main-content_left-list-item
          電話番号の確認
          %i.fas.fa-chevron-right
    %li
      = link_to log_out_users_path do
        .main-content_left-list-item
          ログアウト
          %i.fas.fa-chevron-right
             