config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                 registrations: 'users/registrations' }

  root 'items#index'
  resources :users do
    collection do
      get 'signup'
      get 'mypage_card'
      get 'log_out'
      post 'pay'
    end
  end
  resources :items do
    collection do
      get 'edit_user_info'
      get 'profile_edit'
      get 'purchase'
      get 'search'
      get 'item_confirmation'
    end
  end
  namespace :api do
    resources :items, only: :new, defaults: {format: 'json'}
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

   resources :purchase, only: [:index] do
      collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
      end
    end

  resources :exchanges, only: [:show] do
    collection do
      get 'listing_confirmation'
      get 'trading'
      get 'sold'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :images
  has_many_attached :images
  belongs_to :category

  validates_presence_of :name, :text, :images, :price

  enum prefecture: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController
  def new
    @secondCategories = Category.where(ancestry: params[:firstCat])
    @thirdCategories = Category.where(ancestry: "#{params[:firstCat]}/#{params[:secondCat]}")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :destroy, :edit, :update]
  before_action :set_parent

  def index
    if user_signed_in?
      @items = Item.where.not(user_id: current_user.id).order("RAND()").limit(4)
      @ladys = Item.where.not(user_id: current_user.id).where(category_id: 16..137).order(id: "DESC").limit(4)
      @mens = Item.where.not(user_id: current_user.id).where(category_id: 153..258).order(id: "DESC").limit(4)
      @books = Item.where.not(user_id: current_user.id).where(category_id: 522..567).order(id: "DESC").limit(4)
      @hobbys = Item.where.not(user_id: current_user.id).where(category_id: 575..612).order(id: "DESC").limit(4)
    else
      @items = Item.order("RAND()").limit(4)
      @ladys = Item.where(category_id: 16..137).order(id: "DESC").limit(4)
      @mens = Item.where(category_id: 153..258).order(id: "DESC").limit(4)
      @books = Item.where(category_id: 522..567).order(id: "DESC").limit(4)
      @hobbys = Item.where(category_id: 575..612).order(id: "DESC").limit(4)
    end
  end

  def new
    @item = Item.new
  end

  def create
    @items = Item.create(item_params)
    redirect_to listing_confirmation_exchanges_path
  end

  def edit_user_info

  end

  def profile_edit

  end


  def show
    @user = @item.user
    @other_items = Item.where.not(id: params[:id]).order('id DESC').first(6)
    @image = @item.images.first
  end


  def edit
  end

  def update
    if @item.user_id == current_user.id
      @item.update(item_params)
      flash[:notice] = "商品情報を編集しました"
      redirect_to item_confirmation_items_path(@item)
    else
      flash[:notice] = "権限がありません"
      redirect_to  edit_item_path
    end

  end


  def search
    @items = Item.where("name LIKE(?)", "%#{params[:keyword]}%") unless params[:keyword] == ""
    @word = params[:keyword]
    @new_items = Item.all.order('id DESC').limit(48)
  end

  def item_confirmation
    @item = Item.find(params[:format])
    @user = @item.user
    @image = @item.images.first
  end

  def destroy
    if @item.user_id == current_user.id
      if @item.destroy
        redirect_to listing_confirmation_exchanges_path
      else
        flash[:notice] = "削除に失敗しました"
        render 'exchanges/listing_confirmation'
      end
    end

  end

  private

  def item_params
    params.require(:item).permit(:name, :text, :state, :delivery_fee, :shipping, :price, :category_id, :prefecture, images: []).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_parent
    @parents = Category.where(ancestry: nil)
  end
end

app/views/items/edit_user_info.html.haml
.edit-user-info-container

  .toppage-header
    = render 'shared/header'
  %nav.main-content__breadcrumb
    - breadcrumb :edit_user_info
    = breadcrumbs separator: "#{content_tag(:i, '', class: 'fas fa-chevron-right')}"

  .profile-main
    .main-profile
      .left-content
        = render 'shared/sidebar'
      .right-side
        .right-side__header 本人情報の登録
        .right-side__main
          .right-side__main__description
            .right-side__main__description__text お客さまの本人情報をご登録ください。</br>登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            = link_to "本人確認書類のアップロードについて", "#", class:"description-rink"
          .right-side__main__info
            .label.right-side__main__info__title お名前
            .right-side__main__info__content 田中 太郎
          .right-side__main__info
            .label.right-side__main__info__title お名前カナ
            .right-side__main__info__content タナカ タロウ
          .right-side__main__info
            .label.right-side__main__info__title 生年月日
            .right-side__main__info__content 1111/11/11
          .right-side__main__info
            .right-side__main__info__title
              .label.right-side__main__info__title__label 郵便番号
              .right-side__main__info__title__note 任意
            %input{type:"text", placeholder:"例）1234567", class:"edit-form"}
          .right-side__main__info
            .right-side__main__info__title
              .label.right-side__main__info__title__label 都道府県
              .right-side__main__info__title__note 任意
            %input{type:"text", placeholder:"--", class:"edit-form"}
          .right-side__main__info
            .right-side__main__info__title
              .label.right-side__main__info__title__label 市区町村
              .right-side__main__info__title__note 任意
            %input{type:"text", placeholder:"例) 横浜市緑区", class:"edit-form"}
          .right-side__main__info
            .right-side__main__info__title
              .label.right-side__main__info__title__label 番地
              .right-side__main__info__title__note 任意
            %input{type:"text", placeholder:"例) 青山1−1−1", class:"edit-form"}
          .right-side__main__info
            .right-side__main__info__title
              .label.right-side__main__info__title__label 建物名
              .right-side__main__info__title__note 任意
            %input{type:"text", placeholder:"例) 柳ビル103", class:"edit-form"}
          .right-side__main__btn
            %input{type:"submit", value:"登録する", class:"edit-btn"}
          .right-side__main__description
            = link_to "本人情報の登録について", "#", class:"description-rink"
  .toppage-aside
    = render 'shared/aside'

  .toppage-footer
    = render 'shared/footer'

  = link_to new_item_path do
    .footer-sell-btn
      .footer-sell-box
        .sell-text 出品
        .fa.fa-camera

app/views/items/index.html.haml
.toppage-container

  .toppage-header
    = render 'shared/header'

  .toppage-main
    = render 'shared/main'

  .toppage-aside
    = render 'shared/aside'

  .toppage-footer
    = render 'shared/footer'

  = link_to new_item_path do
    .footer-sell-btn
      .footer-sell-box
        .sell-text 出品
        .fa.fa-camera

app/views/items/item_confirmation.html.haml
.product-container

  .toppage-header
    = render 'shared/header'

  .product-main
    .main-detail
      %section.detail-content
        .detail-content__header
          = @item.name
        .detail-content__main
          .detail-content__main__image
            = image_tag @image ,class:"main"
            .detail-content__main__image__box
              - @item.images.each do |image|
                = image_tag image ,class:"sub", style: "width:55px"
          .detail-content__main__table
            %table.detail-content__main__table__main
              %tr
                %th 出品者
                %td
                  = link_to "#{@user.nickname}",  class:"table-username"
                  .user-evaluation
                    .good-icon
                      .fa.fa-smile-o#good-icon
                      .good-count 0
                    .normal-icon
                      .fa.fa-meh-o#normal-icon
                      .good-count 0
                    .bad-icon
                      .fa.fa-frown-o#bad-icon
                      .good-count 0
              %tr
                %th カテゴリー
                %td
                  = link_to "#", class:"link-category" do
                    = @item.category.parent.parent.name
                  = link_to "#", class:"fa fa-angle-right link-category" do
                    = @item.category.parent.name
                  = link_to "#", class:"fa fa-angle-right link-category" do
                    = @item.category.name
              %tr
                %th 商品の状態
                %td 
                  = @item.state
              %tr
                %th 配送料の負担
                %td 
                  = @item.delivery_fee
              %tr
                %th 配送の方法
                %td らくらくメルカリ便
              %tr
                %th 配送元地域
                %td
                  = link_to "#{@item.prefecture}", "#"
              %tr
                %th 発送日の目安
                %td 
                  = @item.shipping

        .detail-content__price
          .detail-content__price__main
            .yen-mark ¥
            = number_with_delimiter(@item.price)
          .detail-content__price__tax (税込)
          .detail-content__price__fee
            = @item.delivery_fee
        .detail-content__description
          .detail-content__description__inner
            = @item.text
        
      %section.detail-listing
        .detail-listing__btn
          = link_to '商品の編集', edit_item_path(@item),  class:"detail-red-btn"
        .detail-listing__text or
        .detail-listing__btn
          = link_to 'この商品を削除する', item_path(@item), class:"detail-gray-btn", method: :delete

      %section.detail-comment
        .detail-comment__note 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        .detail-comment__textarea
          %textarea{id:"comment-textarea"}
        .detail-comment__btn
          %input{type:"submit", value:"コメントする", id:"comment-btn"}

  .toppage-aside
    = render 'shared/aside'

  .toppage-footer
    = render 'shared/footer'

app/views/items/new.html.haml
.container
  %header.container__header
    .container__header__logo
      = link_to root_path do
        = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?570108281", alt: "mercari")


  = form_with(url: items_path, model: @item, local: true, class: "new-item", id:"new-item") do |f|

    .container__main__container
      .container__main__container__sell
        %h2.container__main__container__sell__title 商品の情報を入力
        %form.container__main__container__sell__form
          .container__main__container__sell__form__content
            .container__main__container__sell__form__content__upload__box
              %h3.container__main__container__sell__form__content__upload__box__head
                出品画像
                %span.container__main__container__sell__form__content__upload__box__head__require 必須
                %p 最大10枚までアップロードできます
              .container__main__container__sell__form__content__upload__box__drop__box
                %ul.preview
                .image-grid-box
                  = f.label :images, for: "images-file1", id:"images_field" do
                    .container__main__container__sell__form__content__upload__box__drop__box__content
                      %p.container__main__container__sell__form__content__upload__box__drop__box__content__text
                      %p.container__main__container__sell__form__content__upload__box__drop__box__content__text
                        クリックしてファイルをアップロード
                    = f.file_field :images, multiple: true, id:"images-file1", style: "display:none"
              #itemimage_uproad_over アップロードできる画像は10枚までです。
              #itemimage_uproad_none 画像がありません
        .container__main__container__sell__form__item
          = f.label :商品名, class:"container__main__container__sell__form__item__title"
          %span.container__main__container__sell__form__item__title__require 必須
          %div
            = f.text_field :name, class:"container__main__container__sell__form__item__title__input__default", placeholder:  "商品名（必須 40文字まで)", value: ""
        .container__main__container__sell__form__item__discription
          = f.label :商品の説明, class:"container__main__container__sell__form__item__discription"
          %span.container__main__container__sell__form__item__discription__title__require 必須
          = f.text_area :text, class:"container__main__container__sell__form__item__discription__title__textarea", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "5"
        .container__main__container__sell__form__show#show-margin
          %h3.container__main__container__sell__form__show__title 商品の詳細
          .container__main__container__sell__form__show__right__box
            .container__main__container__sell__form__show__right__box__group__category
              = f.label :カテゴリー, class:"container__main__container__sell__form__show__right__box__group__category__title"
              %span.container__main__container__sell__form__show__right__box__group__category__require 必須
              %div
                .container__main__container__sell__form__show__right__box__group__category__select__wrap
                  = f.select :category_id, Category.where(ancestry: nil).map{|c| [c.name, c.id]}, { include_blank: "---" }, {id: "selectitembox"}
                  = f.select :category_id, {}, { include_blank: "---" }, {id: "selectitembox1", style: "display: none"}
                  = f.select :category_id, {}, { include_blank: "---" }, {id: "selectitembox2", style: "display: none"}
                  %i.container__main__container__sell__form__show__right__box__group__category__select__wrap__icon__arrow__bottom
            .container__main__container__sell__form__show__right__box__group__condition#state-margin
              = f.label :商品の状態, class:"container__main__container__sell__form__show__right__box__group__condition__title"
              %span.container__main__container__sell__form__show__right__box__group__condition__require 必須
              .container__main__container__sell__form__show__right__box__group__condition__select__wrap
                = f.select :state, ["新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], { include_blank: "---" },
                  class:"container__main__container__sell__form__show__right__box__group__condition__select__wrap__select__default"
                %i.container__main__container__sell__form__show__right__box__group__condition__select__wrap__icon__arrow__bottom
        .container__main__container__sell__form__delivery
          %h3.container__main__container__sell__form__delivery__title 配送について
          = link_to  "", class: "container__main__container__sell__form__delivery__question" do
            =fa_icon("question-circle")
          .container__main__container__sell__form__delivery__right__box
            .container__main__container__sell__form__delivery__right__box__fee
              = f.label :配送料の負担, class:"container__main__container__sell__form__delivery__right__box__fee__title"
              %span.container__main__container__sell__form__delivery__right__box__fee__require 必須
              .container__main__container__sell__form__delivery__right__box__fee__select__wrap
                = f.select :delivery_fee, ["送料込み", "着払い"] ,{ include_blank: "---" },
                  class:"container__main__container__sell__form__delivery__right__box__fee__select__wrap__default"
                %i.container__main__container__sell__form__delivery__right__box__fee__select__wrap__icon__arrow__bottom
            .container__main__container__sell__form__delivery__right__box__area
              = f.label :発送元の地域, class:"container__main__container__sell__form__delivery__right__box__area__title"
              %span.container__main__container__sell__form__delivery__right__box__area__require 必須
              .container__main__container__sell__form__delivery__right__box__area__select__wrap
                = f.select :prefecture, Item.prefectures.keys, class: "container__main__container__sell__form__delivery__right__box__area__select__wrap__default"
            .container__main__container__sell__form__delivery__right__box__days
              = f.label :発送までの日数, class:"container__main__container__sell__form__delivery__right__box__days__title"
              %span.container__main__container__sell__form__delivery__right__box__days__require 必須
              .container__main__container__sell__form__delivery__right__box__days__select__wrap
                = f.select :shipping, ["1~2日で発送", "2~3日で発送", "4~7日で発送"] ,{ include_blank: "---" },
                  class:"container__main__container__sell__form__delivery__right__box__days__select__wrap__default"
                %i.container__main__container__sell__form__delivery__right__box__days__form__require__select__wrap__icon__arrow__bottom
        .container__main__container__sell__form__price
          %h3.container__main__container__sell__form__price__title 販売価格(300〜9,999,999)
          = link_to  "", class: "container__main__container__sell__form__price__question" do
            =fa_icon("question-circle")
          .container__main__container__sell__form__price__right__box
            %ul.container__main__container__sell__form__price__right__box__sell__price
              %li.container__main__container__sell__form__price__right__box__sell__price__form__group
                .container__main__container__sell__form__price__right__box__sell__price__form__group__item__price
                  = f.label :価格, class:"container__main__container__sell__form__price__right__box__sell__price__title"
                  %span.container__main__container__sell__form__price__right__box__sell__price__require 必須
                  .container__main__container__sell__form__price__right__box__sell__price__form__group__item__price__input
                    ¥
                    %div
                      = f.text_field :price, class:"container__main__container__sell__form__price__right__box__sell__price__form__group__item__price__input__default", placeholder: "例）300", value: ""
              %li.container__main__container__sell__form__price__right__box__sell__price__form__group__margin
                .container__main__container__sell__form__price__right__box__sell__price__form__group__margin__left
                  販売手数料 (10%)

                  .container__main__container__sell__form__price__right__box__sell__price__form__group__margin__right#price_fee -
              %li.container__main__container__sell__form__price__right__box__sell__price__form__group__profit
                .container__main__container__sell__form__price__right__box__sell__price__form__group__profit__left 販売利益
                .container__main__container__sell__form__price__right__box__sell__price__form__group__profit__right#sales_profit -

        .container__main__container__sell__form__btn__box
          .container__main__container__sell__form__btn__box__info
            %p
              =link_to  "禁止されている出品", "#", target: "_blank"
              、
              =link_to "行為",  target: "_blank"
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              =link_to  "偽ブランドの販売", target: "_blank"
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              =link_to "加盟店規約" 
              に同意したことになります。
          = f.submit '出品する', class:"container__main__container__sell__form__btn__box__btn__red"
          = link_to "もどる", root_path, class:"container__main__container__sell__form__btn__box__btn__gray"
      .overlay
  %footer.agreement__footer
    %nav.footer__nav
      %ul.footer__nav__content
        %li
          =link_to  "プライバシーポリシー", "#"
        %li
          =link_to "メルカリ利用規約", "#"
        %li
          =link_to  "特定商取引に関する表記", "#"
    =link_to "", class: "single-footer-logo" do
      =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?570108281", alt: "mercari", height: "65", width: "80")
    %p
      %small © 2019 Mercari

app/views/items/show.html.haml
.product-container

  .toppage-header
    = render 'shared/header'
  %nav.main-content__breadcrumb
    - breadcrumb :show
    = breadcrumbs separator: "#{content_tag(:i, '', class: 'fas fa-chevron-right')}"
  .product-main
    .main-detail
      %section.detail-content
        .detail-content__header
          = @item.name
        .detail-content__main
          .detail-content__main__image
            - if @item.trade == true
              .sold-out
            = image_tag @image ,class:"main"
            .detail-content__main__image__box
              - @item.images.each do |image|
                = image_tag image ,class:"sub", style: "width:55px"
          .detail-content__main__table
            %table.detail-content__main__table__main
              %tr
                %th 出品者
                %td
                  = link_to "#{@user.nickname}",  class:"table-username"
                  .user-evaluation
                    .good-icon
                      .fa.fa-smile-o#good-icon
                      .good-count 90
                    .normal-icon
                      .fa.fa-meh-o#normal-icon
                      .good-count 8
                    .bad-icon
                      .fa.fa-frown-o#bad-icon
                      .good-count 5
              %tr
                %th カテゴリー
                %td
                  = link_to "#", class:"link-category" do
                    = @item.category.parent.parent.name
                  = link_to "#", class:"fa fa-angle-right link-category" do
                    = @item.category.parent.name
                  = link_to "#", class:"fa fa-angle-right link-category" do
                    = @item.category.name
              %tr
                %th 商品の状態
                %td 
                  = @item.state
              %tr
                %th 配送料の負担
                %td 
                  = @item.delivery_fee
              %tr
                %th 配送の方法
                %td らくらくメルカリ便
              %tr
                %th 配送元地域
                %td
                  = link_to "#{@item.prefecture}", "#"
              %tr
                %th 発送日の目安
                %td 
                  = @item.shipping

        .detail-content__price
          .detail-content__price__main
            .yen-mark ¥
            = number_with_delimiter(@item.price)
          .detail-content__price__tax (税込)
          .detail-content__price__fee 送料込み
        - unless @item.user_id == current_user.id
          - if @item.trade == false
            .detail-content__btn
              = link_to "購入画面に進む", purchase_index_path(@item), class:"detail-show-btn"
          - else
            .detail-content__btn
              .detail-sold-btn 売り切れました
        .detail-content__description
          .detail-content__description__inner
            = @item.text
        .detail-content__buttons
          .detail-content__buttons__left
            .detail-content__buttons__left__like.fa.fa-heart-o いいね! 7
            .detail-content__buttons__left__report.fa.fa-flag-o 不適切な商品の報告
          .detail-content__buttons__right
            = link_to "あんしん・あんぜんへの取り組み", "#", class:"detail-content__buttons__right__link fa fa-lock"
      %section.detail-comment
        .detail-comment__main
          .detail-comment__main__icon
            = link_to "#" do
              = image_tag "mypage.png", id:"comment-icon"
          .detail-comment__main__content
            .detail-comment__main__content__name ユーザーネーム
            .detail-comment__main__content__body
              .detail-comment__main__content__body__text 出品者がコメントを削除しました<br>出品者がコメントを削除しました
              .detail-comment__main__content__body__icons
                .detail-comment__main__content__body__icons__left.fa.fa-clock-o 181日前
                = link_to "#" do
                  .fa.fa-flag-o
        .detail-comment__main
          .detail-comment__main__icon
            = link_to "#" do
              = image_tag "mypage.png", id:"comment-icon"
          .detail-comment__main__content
            .detail-comment__main__content__name ユーザーネーム
            .detail-comment__main__content__body
              .detail-comment__main__content__body__text 出品者がコメントを削除しました<br>出品者がコメントを削除しました
              .detail-comment__main__content__body__icons
                .detail-comment__main__content__body__icons__left.fa.fa-clock-o 181日前
                = link_to "#" do
                  .fa.fa-flag-o
        .detail-comment__note 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        .detail-comment__textarea
          %textarea{id:"comment-textarea"}
        .detail-comment__btn
          %input{type:"submit", value:"コメントする", id:"comment-btn"}
      %section.detail-link
        = link_to "#", class:"detail-link__left" do
          .fa.fa-angle-left
          .detail-link__left__text ディズニーヴィランズ 2個セット バッジ バッチ Villains 2018
        = link_to "#", class:"detail-link__right" do
          .detail-link__right__text 楽天パンダ ノート&マスキングテープセット
          .fa.fa-angle-right.detail-link__right__icon
      %section.detail-icon
        .detail-icon__faceebook
          = link_to "http://www.facebook.com/share.php?u=https%3A%2F%2Fitem.mercari.com%2Fjp%2Fm66888862498%2FQ", target:"_blank" do
            = image_tag "facebook-icon.png", class:"facebook-icon"
        .detail-icon__twitter
          = link_to "http://twitter.com/share?count=horizontal&original_referer=https%3A%2F%2Fitem.mercari.com%2Fjp%2Fm66888862498%2F&text=%E3%83%A1%E3%83%B3%E3%82%BA%20%E6%B5%B7%E3%83%91%E3%83%B3%20%28%C2%A5%201%2C700%29%20https%3A%2F%2Fitem.mercari.com%2Fjp%2Fm66888862498%2F%20%E3%83%95%E3%83%AA%E3%83%9E%E3%82%A2%E3%83%97%E3%83%AA%E3%80%8C%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA%E3%80%8D%E3%81%A7%E8%B2%A9%E5%A3%B2%E4%B8%AD%E2%99%AA%20%23%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA%20%40mercari_jp%E3%81%95%E3%82%93%E3%81%8B%E3%82%89", target:"_blank" do
            = image_tag "twitter-icon.png", class:"twitter-icon"
        .detail-icon__pinterest
          = link_to "http://pinterest.com/pin/create/button/?url=https%3A%2F%2Fitem.mercari.com%2Fjp%2Fm66888862498%2F&media=https%3A%2F%2Fstatic.mercdn.net%2Fitem%2Fdetail%2Forig%2Fphotos%2Fm66888862498_1.jpg%3F1556435256&description=%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA%E5%95%86%E5%93%81%3A%20%E3%83%A1%E3%83%B3%E3%82%BA%20%E6%B5%B7%E3%83%91%E3%83%B3%20%23%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA", target:"_blank" do
            = image_tag src="pinterest-icon.png", class:"pinterest-icon"
      %section.detail-box-container
        .text-center
          = link_to "#{@user.nickname}さんのその他の商品", "/jp/category/2/"
        .items-box-content
          - @other_items.each do |item|
            %section.items-box
              = link_to item_path(item) do
                .items-box__photo
                  = image_tag item.images.first, class:"items-photo"
                .items-box__body
                  .items-box__body__name
                    = item.name
                  .items-box__body__num
                    .items-box__body__num__price.font-5
                      .yen-mark ¥
                      = item.price
                    .todo-icon
                      .fa.fa-heart-o
                      %span 7
                  %p.items-box__body__tax (税込)
      %section.detail-box-container
        .text-center
          = link_to "カテゴリー その他の商品", "/jp/category/2/"
        .items-box-content
          %section.items-box
            = link_to "#" do
              .items-box__photo
                = image_tag "fig9.jpg", class:"items-photo"
              .items-box__body
                .items-box__body__name ※更に値下げ！リーボック子供ブーツ
                .items-box__body__num
                  .items-box__body__num__price.font-5 ¥ 300
                  .todo-icon
                    .fa.fa-heart-o
                    %span 1
                %p.items-box__body__tax (税込)
          %section.items-box
            = link_to "#" do
              .items-box__photo
                = image_tag "fig13.jpeg", class:"items-photo"
              .items-box__body
                .items-box__body__name 雪花秀 乳液&amp;化粧水 40本セット
                .items-box__body__num
                  .items-box__body__num__price.font-5 ¥ 2,300
                %p.items-box__body__tax (税込)
          %section.items-box
            = link_to "#" do
              .items-box__photo
                = image_tag "fig11.jpg", class:"items-photo"
              .items-box__body
                .items-box__body__name kids用半袖Tシャツ サイズ90
                .items-box__body__num
                  .items-box__body__num__price.font-5 ¥ 450
                  .todo-icon
                    .fa.fa-heart-o
                    %span 2
                %p.items-box__body__tax (税込)
          %section.items-box
            = link_to "#" do
              .items-box__photo
                = image_tag "fig12.jpg", class:"items-photo"
              .items-box__body
                .items-box__body__name コート
                .items-box__body__num
                  .items-box__body__num__price.font-5 ¥ 1,500
                %p.items-box__body__tax (税込)
          %section.items-box
            = link_to "#" do
              .items-box__photo
                = image_tag "fig14.jpg", class:"items-photo"
              .items-box__body
                .items-box__body__name MKUP 台湾 素顔クリーム
                .items-box__body__num
                  .items-box__body__num__price.font-5 ¥ 4,200
                %p.items-box__body__tax (税込)
          %section.items-box
            = link_to "#" do
              .items-box__photo
                = image_tag "fig15.jpg", class:"items-photo"
              .items-box__body
                .items-box__body__name キャンメイク パウダーアイライナー 02
                .items-box__body__num
                  .items-box__body__num__price.font-5 ¥ 400
                %p.items-box__body__tax (税込)


  .toppage-aside
    = render 'shared/aside'

  .toppage-footer
    = render 'shared/footer'