config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                 registrations: 'users/registrations' }

  root 'items#index'
  resources :users do
    collection do
      get 'signup'
      get 'mypage_card'
      get 'log_out'
      post 'pay'
    end
  end
  resources :items do
    collection do
      get 'edit_user_info'
      get 'profile_edit'
      get 'purchase'
      get 'search'
      get 'item_confirmation'
    end
  end
  namespace :api do
    resources :items, only: :new, defaults: {format: 'json'}
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

   resources :purchase, only: [:index] do
      collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
      end
    end

  resources :exchanges, only: [:show] do
    collection do
      get 'listing_confirmation'
      get 'trading'
      get 'sold'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/card_controller.rb
class CardController < ApplicationController

  before_action :set_parent, only: [:new, :show]
require "payjp"
  def new
    @parents = Category.where(ancestry: nil)
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成
    Payjp.api_key =  "sk_test_339f6fe8466e202736fdbf30"
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def show
     card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = "sk_test_339f6fe8466e202736fdbf30"
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = "sk_test_339f6fe8466e202736fdbf30"
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def set_parent
    @parents = Category.where(ancestry: nil)
  end
end

app/views/card/new.html.haml
.mypage-card-create-container
  .card-create-header
    = render 'shared/header' 
    %nav.header-card
      %ul
        %li
          =link_to "メルカリ", "#"
          =fa_icon("angle-right")
        %li
          =link_to "マイページ", "#"
          =fa_icon("angle-right")
        %li
          =link_to "支払い方法", "#"
          =fa_icon("angle-right")
        %li
          %span クレジットカード情報入力
  .card-create-main.center
    .content-box
      .card-create-side
        = render 'shared/sidebar'
      .card-registration
        %h2.card-registration__title クレジットカード情報入力
        = form_tag(pay_card_index_path, method: :post, id: 'charge-form', class: 'card-registration__form',  name: "inputForm") do
          .content__box
            .content__box__group
              %label カード番号
              %span.content__box__group__form__require 必須
              %br
              %input.content__box__group__input{"data-input-type" => "card", maxlength: "16", placeholder: "半角数字のみ", type: "text",name: "card_number",id: "payment_card_no"}/
              %ul.content__box__group__card__list
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?4194600336", height:"20", width: "49")
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?4194600336", height:"20", width: "34")
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?4194600336", height:"20", width: "30")  
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?4194600336", height: "20", width: "32") 
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?4194600336", height: "20", width: "21")  
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?4194600336", height: "20", width: "32")
                %li
                  =image_tag("//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?4194600336", height: "20", width: "32") 
              .content__box__expire
                %label{for: "payment_card_expire"} 有効期限
                %span.content__box__expire__require 必須
                %br/
                .content__box__expire__box
                  .content__box__expire__box__month
                    %select{name: "exp_month",id: "payment_card_expire_mm"}
                      %option{value:  "01"} 01
                      %option{value:  "02"} 02
                      %option{value:  "03"} 03
                      %option{value:  "04"} 04
                      %option{value:  "05"} 05
                      %option{value:  "06"} 06
                      %option{value:  "07"} 07
                      %option{value:  "08"} 08
                      %option{value:  "09"} 09
                      %option{value:  "10"} 10
                      %option{value:  "11"} 11
                      %option{value:  "12"} 12
                  %p 月
                .content__box__expire__box
                  .content__box__expire__box__year
                    %select.exp_year{name: "exp_year",id: "payment_card_expire_yy"}
                      %option{value:  "19"} 19
                      %option{value:  "2020"} 20
                      %option{value:  "2021"} 21
                      %option{value:  "2022"} 22
                      %option{value:  "2023"} 23
                      %option{value:  "2024"} 24
                      %option{value:  "2025"} 25
                      %option{value:  "2026"} 26
                      %option{value:  "2027"} 27
                      %option{value:  "2028"} 28
                      %option{value:  "2029"} 29
                  %p 年
              .content__box__secure
                %label{for:  "payment_card_security_code"} セキュリティコード
                %span.content__box__secure__require 必須
                %input.content__box__secure__default{placeholder: "カード背面4桁もしくは3桁の番号", type:  "number", value:  "",name: "cvc",id: "payment_card_security_code"}/
                .content__box__secure__box
                  .content__box__secure__box__text{"data-js" => "show-tips-toggle"}
                    %span
                      =fa_icon("question-circle")
                    カード裏面の番号とは？
    
                  .content__box__secure__box__hidden{"data-js" => "show-tips-content"}
                    カードの裏面をご参照ください。
                    %br/
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?4194600336", :width => "240"
                  -# = submit_tag "追加する", id: "token_submit", class: "btn-default btn-red"
                  %button.ur-form__btn--submit{type: "submit",id: "token_submit"} 次へ進む

  .toppage-aside
    = render 'shared/aside'
  .toppage-footer
    = render 'shared/footer'

  = link_to new_item_path do
    .footer-sell-btn
      .footer-sell-box
        .sell-text 出品
        .fa.fa-camera

app/views/card/show.html.haml
.toppage-header
  = render 'shared/header'
.main-content
  = render 'shared/sidebar'
  .main-content_right
    .main-content_right_credit
      .main-content_right_credit__head　支払い方法
      .main-content_right_credit__body
        %label 登録クレジットカード情報
        %figure
          %img{:alt => "visa", :height => "15", :src => "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?376951604", :width => "49"}/
        %br
        = "**** **** **** " + @default_card_information.last4
        %br
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
        = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button 削除する